site_name: My Docs
repo_url: https://github.com/your-username/mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - toc.follow
    - content.code.annotate
    - content.action.edit

  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
        
markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - extra/styles.css

extra:
  translation:
    banner: false