site_name: My Docs
repo_url: https://github.com/therepos/mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - toc.follow
    - content.code.annotate
    - content.action.edit

  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono

plugins:
  - search
  - awesome-pages
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: medium
  - git-revision-date-localized:
      type: timeago
  - redirects:
      redirect_maps:
        index.md: about/index.md
        
markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - toc:
      permalink: true

extra_css:
  - css/styles.css

extra:
  translation:
    banner: false