site_name: MkDocs
repo_url: https://github.com/therepos/mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - toc.follow
    - content.code.annotate
    - content.action.edit
    - content.code.copy

  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono

plugins:
  - search
  - awesome-pages
  - blog:
      archive_date_format: MMM yyyy
      blog_toc: true
      post_date_format: medium
      archive_name: Timeline
  - tags
  - git-revision-date-localized:
      type: timeago
  - redirects:
      redirect_maps:
        index.md: about/index.md
        
markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - codehilite
  - toc:
      permalink: true

extra_css:
  - css/styles.css

extra:
  translation:
    banner: false

copyright: |
    <span style="display: inline-flex; align-items: center;">
      <img src="https://licensebuttons.net/l/by/4.0/88x31.png" alt="Creative Commons License" style="height: 24px; margin-right: 8px;">
      © 2025 by Your Name or Organization — Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>
    </span>